### ISSUE TITLE
Missing iPhone X series support

### ISSUE THREAD

**Issue by moiz212** [invoiceninja/flutter-client#149] opened 2020-08-30 17:31 UTC
Hello, 
I'm running app in demo mode from develop latest code having below error, please look at screenshot, Thanks :-)
<img width="518" alt="Screenshot 2020-08-30 at 10 59 03 PM" src="https://user-images.githubusercontent.com/51788555/91665637-b6fb0980-eb14-11ea-9932-021167987a8e.png">

**Comment by hillelcoren** [comment] 2020-08-30 17:34
Not sure it's an error, there just isn't much test data

**Comment by moiz212** [comment] 2020-08-30 18:04
Getting black part on top and bottom, this screen doesn't have iPhone X Series support

**Comment by moiz212** [comment] 2020-08-30 18:05
Other screen are working fine, its great if you an fix it  :-)

**Comment by hillelcoren** [comment] 2020-08-30 18:19
Can you please post a sample of what other screens look like for you?

**Comment by moiz212** [comment] 2020-08-30 18:22
Have a look at these Images all have top and Bottom in white color matching the entire screen
<img width="518" alt="Screenshot 2020-08-30 at 11 50 30 PM" src="https://user-images.githubusercontent.com/51788555/91666602-bade5a00-eb1b-11ea-8fa8-a4d2677d33c5.png">
<img width="518" alt="Screenshot 2020-08-30 at 11 50 40 PM" src="https://user-images.githubusercontent.com/51788555/91666603-bc0f8700-eb1b-11ea-9771-f022459d414f.png">

**Comment by moiz212** [comment] 2020-09-01 11:14
Hi,
can you please help me on this.?

**Comment by hillelcoren** [comment] 2020-09-01 11:17
It's probably caused by an unneeded SafeArea widget somewhere.

We'll try to include a fix with our next release.

**Comment by moiz212** [comment] 2020-09-02 12:11
I have fixed that its because of this below code:-
   /* DashboardScreenBuilder.route: (context) => ChangeLayoutBanner(
                        suggestedLayout: AppLayout.mobile,
                        appLayout: state.prefState.appLayout,
                        child: DashboardScreenBuilder(),
                      ),*/ 
I change this to :- DashboardScreenBuilder.route: (context) =>
                      DashboardScreenBuilder(), in main_app.dart file

**Comment by moiz212** [comment] 2020-09-02 12:14
also added this below code for another bug of status bar text getting hidden in every screen with white app bar like in above image:-
 brightness: hasAccentColor ? Brightness.dark : Brightness.light, on appBarTheme: AppBarTheme in main_app.dart

**Comment by hillelcoren** [comment] 2020-09-02 13:38
I've checked in a change which should help

**Comment by moiz212** [comment] 2020-09-02 13:56
Hi, I'm getting socket error when using self hosted login and what to add in entry dns

**Comment by hillelcoren** [comment] 2020-09-02 14:24
Can I ask your plans with the app, how are you using it?

**Comment by moiz212** [comment] 2020-09-03 11:48
we have a self hosted account, and when login I am seeing loader no data, can you please help me
<img width="518" alt="Screenshot 2020-09-03 at 5 17 27 PM" src="https://user-images.githubusercontent.com/51788555/92111085-64b63300-ee09-11ea-9dae-f75772b28438.png">

**Closed** 2020-11-24 10:00 UTC
Labels: bug
